logging:
    level:
        ROOT: INFO
        org.springframework: WARN
        org.apache.catalina: WARN
        org.springframework.boot.web.embedded.tomcat.TomcatWebServer: INFO

spring:
    application:
        name: govmon
    security:
        user:
            name: user
            password: pass
            roles: ACTUATOR, USER   # or any other role
    mvc:
        throw-exception-if-no-handler-found: true
    jpa:
        database-platform: org.hibernate.dialect.MySQLDialect
    datasource:
        url: jdbc:mysql://localhost:3306/govmon
        username: moni
        password: password
    hibernate:
        dialect: mysql

monitor:
    government:
        mfcr:
            server:
                scheme: https
                host: monitor.statnipokladna.cz
                port:
                path: /api
            reports:
                organization:
                    path: /ucetni-jednotka
                all-statements:
                    path: /ucetni-zaverka/2
                controllable-statements:
                    path: /ucetni-zaverka/2
                    codes: A.I.1, A.I.2, A.I.3, A.I.4, A.I.5, A.I.6, A.I.7, A.I.8, A.I.9, A.I.10, A.I.11, A.I.12, A.I.35, A.I.36


#security:
#    oauth2:
#        client:
#            clientId: a-client
#            clientSecret: the-client-password
#        resource:
#            tokenInfoUri: http://my-spring-oauth2-provider/oauth/check_token

#endpoints:
#    health:
#        sensitive: false

management:
    context-path: /aplication
    security:
        enabled: true

    endpoints:
        web:
            base-path: /application
            exposure:
                include: health,info,routes,auditevents,beans,caches,configprops,env,httptrace,logfile,loggers,liquibase,mappings,sessions
    health:
        roles: ACTUATOR
